
//this file would normally be inside the .gitignore so we don't share our key


const API_KEY = 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjViYmJlMzU5Yjk2ZmUwMDAyM2Y5Y2RiZCIsInVzZXIiOiI1YmJiZTM1OGIyNzdjZjAwMTE4Zjc2MjEiLCJvcmciOiI1YmJiZDhiODZkMjg0ZTAwMTFhNWZlMjEiLCJvcmdOYW1lIjoienp6LWJyeWFuLW8iLCJ1c2VyVHlwZSI6Im1hY2hpbmUiLCJyb2xlcyI6WyJvcmcuYWRtaW4iLCJvcmcudXNlciJdLCJleHAiOjE1NDY4MTk2ODgsImF1ZCI6InVybjpjb25zdW1lciIsImlzcyI6InVybjphcGkiLCJzdWIiOiI1YmJiZTM1OGIyNzdjZjAwMTE4Zjc2MjEifQ.h-gZsDy1g8zl_oLTy3IOYNX1N901l4F1UjJ4PSD2LLM'
